[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.bcmath", "php82Extensions.zip", "php82Extensions.fileinfo", "php82Extensions.tokenizer", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.xml", "php82Extensions.gd", "composer", "git"]

[phases.install]
mode = "replace"
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts"]

[phases.build]
mode = "replace"
cmds = ["echo 'Build Complete'"]

[start]
cmd = "echo 'DEBUG: DB_HOST='$DB_HOST' DB_PORT='$DB_PORT' DB_DATABASE='$DB_DATABASE'' && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
